routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// маршруты админ. панели
Route::group(['prefix'=>'admin', 'namespace'=>'Admin', 'middleware'=>['auth', 'role']], function(){
    Route::get('/', 'DashboardController@dashboard')->name('admin.index');
    Route::group(['prefix'=>'user_managment', 'namespace'=>'UserManagment'], function() {
        Route::resource('/user', 'UserController', ['as' => 'admin.user_managment']);
    });
    Route::resource('/order', 'OrderController', ['as' => 'admin']);
});


Route::get('/start/data-chart', 'Admin\DashboardController@dataChart');

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
// полчаем список материалов
    public static function getAllOrders() {
        // return Order::paginate(3);
        return Order::orderBy('start_date', 'desc')->get();
    }

    // получаем список материалов заказа
    public function materials() {
        return $this->belongsToMany('App\Material')->withPivot('count');
    }

    // получаем филиал, в кот. осуществлен заказ
    public function franchise() {
        return $this->belongsTo('App\Franchise');
    }

}

app/Http/Controllers/Admin/OrderController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Order;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.orders.index', [
            'orders' => Order::paginate(3)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function show(Order $order)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function edit(Order $order)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Order $order)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function destroy(Order $order)
    {
        //
    }
}

resources/views/admin/orders/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">

        <div class="row justify-content-center">
            <div class="col-sm-12">

                <a href="{{route('admin.user_managment.user.create')}}" class="btn btn-primary pull-right"> Создать
                    заказ</a>
                <p></p>
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th scope="col">№ заказа</th>
                        <th scope="col">Франчази</th>
                        <th scope="col">Дата начала</th>
                        <th scope="col">Дата завершения</th>
                        <th scope="col">Изменить</th>
                        <th scope="col">Удалить</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach ($orders as $order)
                        <tr>
                            <td>{{$order->id}}</td>
                            <td>{{$order->franchise->name}}</td>
                            <td>{{$order->start_date}}</td>
                            <td>{{$order->finish_date}}</td>
                            {{--<td>{{$user->roles->implode('name', ', ') }}</td>--}}
                            <td>
                                <a href="{{route('admin.user_managment.user.edit', $order)}}">
                                    <i class="far fa-edit"></i>
                                </a>
                            </td>
                            <td>
                                {{--<form action="{{route('admin.user_managment.user.destroy', $order)}}" method="post"--}}
                                {{--onsubmit="if(confirm('Удалить?')) { return true } else { return false }">--}}
                                {{--{{ csrf_field() }}--}}
                                {{--<input type="hidden" name="_method" value="delete" >--}}
                                {{--{{method_field('DELETE')}}--}}
                                {{--<button type="submit" class="btn"><i class="far fa-trash-alt"></i></button>--}}
                                {{--</form>--}}
                                <a href="#"><i class="far fa-trash-alt"></i></a>

                            </td>


                        </tr>
                        <tr>
                            <td colspan="6">
                                <table class="table">
                                    <thead class="thead-dark">
                                    <tr>
                                        <th scope="col">№ материала</th>
                                        <th scope="col">Наименование</th>
                                        <th scope="col">Цена</th>
                                        <th scope="col">Количество</th>
                                        <th scope="col">Сумма</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    @php ($order_price = 0)
                                    @forelse($order->materials as $material)
                                        <tr>
                                            <th scope="row">{{$material->id}}</th>
                                            <td>{{$material->name}}</td>
                                            <td>{{$price = $material->client_price}}</td>
                                            <td>{{$count = $material->pivot->count}}</td>

                                            @php ($order_price += $price * $count)

                                            <td>{{$price * $count}}</td>
                                        </tr>
                                    @empty
                                        <h6>Материалы данного заказа не добавлены</h6>
                                    @endforelse
                                    <tr>
                                        <td colspan="4"><strong>Итого:</strong></td>
                                        <td>{{$order_price}}</td>
                                    </tr>


                                    </tbody>
                                </table>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                {{$orders->links()}}

            </div>
        </div>
    </div>
@endsection